version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  btd:
    jobs:
      - orb-tools/publish:
          orb-path: src/niva-google-cloud-orb.yml
          orb-ref: nivanorge/niva-google-cloud-orb@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_ZOFIA_API_TOKEN"
          validate: true
          filters:
            branches:
              only: dev
      - orb-tools/increment:
          orb-path: src/niva-google-cloud-orb.yml
          orb-ref: nivanorge/niva-google-cloud-orb
          publish-token-variable: "$CIRCLECI_ZOFIA_API_TOKEN"
          validate: true
          segment: patch
          filters:
            branches:
              only: master